import { QuoteData } from "./quotesList";

export const billionaireQuotes: QuoteData[] = [
  { text: "When something is important enough, you do it even if the odds are not in your favor.", author: "Elon Musk" },
  { text: "Your most unhappy customers are your greatest source of learning.", author: "Bill Gates" },
  { text: "If you’re changing the world, you’re working on important things. You’re excited to get up in the morning.", author: "Larry Page" },
  { text: "It’s fine to celebrate success, but it is more important to heed the lessons of failure.", author: "Bill Gates" },
  { text: "A brand for a company is like a reputation for a person. You earn reputation by trying to do hard things well.", author: "Jeff Bezos" },
  { text: "I choose a lazy person to do a hard job. Because a lazy person will find an easy way to do it.", author: "Bill Gates" },
  { text: "Wealth is not about having a lot of money; it’s about having a lot of options.", author: "Chris Rock" },
  { text: "Risk comes from not knowing what you’re doing.", author: "Warren Buffett" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "Opportunities come infrequently. When it rains gold, put out the bucket, not the thimble.", author: "Warren Buffett" },
  { text: "Every problem is a gift—without problems we would not grow.", author: "Tony Robbins" },
  { text: "The biggest risk is not taking any risk.", author: "Mark Zuckerberg" },
  { text: "If you double the number of experiments you do per year, you’re going to double your inventiveness.", author: "Jeff Bezos" },
  { text: "Failure is another stepping stone to greatness.", author: "Oprah Winfrey" },
  { text: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Richard Branson" },
  { text: "Don't compare yourself with anyone in this world. If you do so, you are insulting yourself.", author: "Bill Gates" },
  { text: "If you’re not stubborn, you’ll give up on experiments too soon. And if you’re not flexible, you’ll pound your head against the wall and you won’t see a different solution to a problem you’re trying to solve.", author: "Jeff Bezos" },
  { text: "I knew that if I failed I wouldn’t regret that, but I knew the one thing I might regret is not trying.", author: "Jeff Bezos" },
  { text: "The secret to success is to know something nobody else knows.", author: "Aristotle Onassis" },
  { text: "You only have to do a very few things right in your life so long as you don’t do too many things wrong.", author: "Warren Buffett" },
  { text: "If you don’t find a way to make money while you sleep, you will work until you die.", author: "Warren Buffett" },
  { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs" },
  { text: "Be nice to geeks. You’ll probably end up working for one.", author: "Bill Gates" },
  { text: "Have the courage to follow your heart and intuition.", author: "Steve Jobs" },
  { text: "Patience is a key element of success.", author: "Bill Gates" },
  { text: "Whether you think you can, or you think you can't – you're right.", author: "Henry Ford" },
  { text: "Vision without execution is hallucination.", author: "Thomas Edison" },
  { text: "It takes 20 years to build a reputation and five minutes to ruin it.", author: "Warren Buffett" },
  { text: "The best investment you can make is in yourself.", author: "Warren Buffett" },
  { text: "The most valuable thing you can make is a mistake – you can't learn anything from being perfect.", author: "Adam Osborne" },
  { text: "I'd rather be optimistic and wrong than pessimistic and right.", author: "Elon Musk" },
  { text: "My biggest mistake is probably weighing too much on someone's talent and not someone’s personality. I think it matters whether someone has a good heart.", author: "Elon Musk" },
  { text: "If you don't understand the details of your business you are going to fail.", author: "Jeff Bezos" },
  { text: "If we were motivated by money, we would have sold the company a long time ago and ended up on a beach.", author: "Larry Page" },
  { text: "Great companies are built on great products.", author: "Elon Musk" },
  { text: "Surround yourself with only people who are going to lift you higher.", author: "Oprah Winfrey" },
  { text: "The biggest adventure you can take is to live the life of your dreams.", author: "Oprah Winfrey" },
  { text: "Don't worry about failure; you only have to be right once.", author: "Drew Houston" },
  { text: "Play by the rules, but be ferocious.", author: "Phil Knight" },
  { text: "In the end, a vision without the ability to execute it is probably a hallucination.", author: "Steve Case" },
  { text: "I am not in competition with anyone but myself. My goal is to improve myself continuously.", author: "Bill Gates" },
  { text: "If you're going through hell, keep going.", author: "Winston Churchill" },
  { text: "The harder I work, the luckier I get.", author: "Samuel Goldwyn" },
  { text: "Giving up is the only sure way to fail.", author: "Gena Showalter" },
  { text: "It’s not about ideas. It’s about making ideas happen.", author: "Scott Belsky" },
  { text: "All our dreams can come true, if we have the courage to pursue them.", author: "Walt Disney" },
  { text: "If you don’t build your dream, someone else will hire you to help them build theirs.", author: "Dhirubhai Ambani" },
  { text: "The way to become rich is to put all your eggs in one basket and then watch that basket.", author: "Andrew Carnegie" },
  { text: "Business opportunities are like buses, there’s always another one coming.", author: "Richard Branson" },
  { text: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
  { text: "Try not to become a man of success, but rather try to become a man of value.", author: "Albert Einstein" },
];
