export interface QuoteData {
  text: string;
  author: string;
}

export const fallbackQuotes: QuoteData[] = [
  // --- Existing Quotes ---
  { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela" },
  { text: "The beautiful thing about learning is that no one can take it away from you.", author: "B.B. King" },
  { text: "Study hard what interests you the most in the most undisciplined, irreverent and original manner possible.", author: "Richard Feynman" },
  { text: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
  { text: "The expert in anything was once a beginner.", author: "Helen Hayes" },
  { text: "Give me six hours to chop down a tree and I will spend the first four sharpening the axe.", author: "Abraham Lincoln" },
  { text: "Whether you think you can or think you can’t, you’re right.", author: "Henry Ford" },
  { text: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
  { text: "Don’t wish it were easier; wish you were better.", author: "Jim Rohn" },
  { text: "You don’t have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
  { text: "The mind is not a vessel to be filled but a fire to be kindled.", author: "Plutarch" },
  { text: "Great things are done by a series of small things brought together.", author: "Vincent Van Gogh" },
  { text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
  { text: "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.", author: "Helen Keller" },
  { text: "All progress takes place outside the comfort zone.", author: "Michael John Bobak" },
  { text: "If you’re going through hell, keep going.", author: "Winston Churchill" },
  { text: "Vision without execution is just hallucination.", author: "Thomas Edison" },
  { text: "Believe you can and you’re halfway there.", author: "Theodore Roosevelt" },
  { text: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
  { text: "Your mind is a powerful thing. When you fill it with positive thoughts, your life will start to change.", author: "Unknown" },
  { text: "Set your goals high, and don't stop till you get there.", author: "Bo Jackson" },
  { text: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen R. Covey" },
  { text: "Dream big and dare to fail.", author: "Norman Vaughan" },
  { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
  { text: "Do not wait to strike till the iron is hot, but make it hot by striking.", author: "William Butler Yeats" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { text: "Quality is not an act, it is a habit.", author: "Aristotle" },
  { text: "Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway.", author: "Earl Nightingale" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Sharpen your sword before the battle begins.", author: "Mindset Proverb" },
  { text: "Motivation gets you started. Habit keeps you going.", author: "Jim Ryun" },
  { text: "Strength and growth come only through continuous effort and struggle.", author: "Napoleon Hill" },
  // --- Quotes of Jesus (from Bible, various translations) ---
  { text: "Love your neighbor as yourself.", author: "Jesus" },
  { text: "With God all things are possible.", author: "Jesus" },
  { text: "I am the way and the truth and the life.", author: "Jesus" },
  { text: "Do to others as you would have them do to you.", author: "Jesus" },
  { text: "Let the one among you who is without sin be the first to cast a stone.", author: "Jesus" },
  { text: "Ask, and it will be given to you; seek, and you will find; knock, and the door will be opened to you.", author: "Jesus" },
  { text: "Blessed are the peacemakers, for they shall be called children of God.", author: "Jesus" },
  { text: "For where your treasure is, there your heart will be also.", author: "Jesus" },
  { text: "Let your light shine before others, that they may see your good deeds and glorify your Father in heaven.", author: "Jesus" },
  { text: "Peace I leave with you; my peace I give you.", author: "Jesus" },
  { text: "Come to me, all who labor and are heavy laden, and I will give you rest.", author: "Jesus" },
  { text: "Do not let your hearts be troubled. Believe in God; believe also in me.", author: "Jesus" },
  { text: "If you have faith as small as a mustard seed, you can say to this mountain, ‘Move from here to there,’ and it will move.", author: "Jesus" },
  { text: "Man shall not live by bread alone, but by every word that proceeds from the mouth of God.", author: "Jesus" },
  { text: "For what shall it profit a man, if he gain the whole world, and suffer the loss of his soul?", author: "Jesus" },
  { text: "Let your yes be yes and your no be no.", author: "Jesus" },
  { text: "By this everyone will know that you are my disciples, if you love one another.", author: "Jesus" },
  { text: "Therefore do not worry about tomorrow, for tomorrow will worry about itself. Each day has enough trouble of its own.", author: "Jesus" },
  { text: "Father, forgive them, for they know not what they do.", author: "Jesus" },
  { text: "Take heart! I have overcome the world.", author: "Jesus" },

  // --- More Mindset/Motivation/Inspirational Quotes ---
  { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "What you do today can improve all your tomorrows.", author: "Ralph Marston" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { text: "Nothing will work unless you do.", author: "Maya Angelou" },
  { text: "Either you run the day or the day runs you.", author: "Jim Rohn" },
  { text: "I can accept failure, everyone fails at something. But I can't accept not trying.", author: "Michael Jordan" },
  { text: "Don't limit your challenges. Challenge your limits.", author: "Unknown" },
  { text: "You don't always get what you wish for. You get what you work for.", author: "Unknown" },
  { text: "If you're tired, learn to rest, not to quit.", author: "Banksy" },
  { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
  { text: "Dreams don’t work unless you do.", author: "John C. Maxwell" },
  { text: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh" },
  { text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
  { text: "You can either experience the pain of discipline or the pain of regret. The choice is yours.", author: "Unknown" },
  { text: "If you don't sacrifice for what you want, what you want becomes the sacrifice.", author: "Unknown" },
  { text: "There are no limits to what you can accomplish, except the limits you place on your own thinking.", author: "Brian Tracy" },
  { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
  { text: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Eleanor Roosevelt" },
  { text: "If opportunity doesn't knock, build a door.", author: "Milton Berle" },
  { text: "It’s not whether you get knocked down, it’s whether you get up.", author: "Vince Lombardi" },
  { text: "A river cuts through rock, not because of its power, but because of its persistence.", author: "James N. Watkins" },
  { text: "If you are going through hell, keep going.", author: "Winston Churchill" },
  { text: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "The starting point of all achievement is desire.", author: "Napoleon Hill" },
  { text: "Perfection is not attainable, but if we chase perfection we can catch excellence.", author: "Vince Lombardi" },
  { text: "Change your thoughts and you change your world.", author: "Norman Vincent Peale" },
  { text: "Every champion was once a contender that refused to give up.", author: "Rocky Balboa" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
  { text: "Make each day your masterpiece.", author: "John Wooden" },
  { text: "Only those who dare to fail greatly can ever achieve greatly.", author: "Robert F. Kennedy" },
  { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { text: "Difficult roads often lead to beautiful destinations.", author: "Zig Ziglar" },
  { text: "Go the extra mile, it's never crowded.", author: "Dr. Wayne D. Dyer" },
  { text: "Success is how high you bounce when you hit bottom.", author: "George S. Patton" },
  { text: "The best revenge is massive success.", author: "Frank Sinatra" },
  { text: "Little minds are tamed and subdued by misfortune; but great minds rise above it.", author: "Washington Irving" },
  { text: "Winners are not people who never fail, but people who never quit.", author: "Unknown" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { text: "Try not to become a man of success, but rather try to become a man of value.", author: "Albert Einstein" },
  { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { text: "The road to success and the road to failure are almost exactly the same.", author: "Colin R. Davis" },
  { text: "Aim for the moon. If you miss, you may hit a star.", author: "W. Clement Stone" },
  { text: "If you hear a voice within you say 'you cannot paint,' then by all means paint, and that voice will be silenced.", author: "Vincent Van Gogh" },
  { text: "There are no traffic jams along the extra mile.", author: "Roger Staubach" },
  { text: "Success is liking yourself, liking what you do, and liking how you do it.", author: "Maya Angelou" },
  { text: "Even if you’re on the right track, you’ll get run over if you just sit there.", author: "Will Rogers" },
  { text: "Do not wait; the time will never be 'just right.'", author: "Napoleon Hill" },
  { text: "You can’t cross the sea merely by standing and staring at the water.", author: "Rabindranath Tagore" },
  { text: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen R. Covey" },
  { text: "Your big opportunity may be right where you are now.", author: "Napoleon Hill" },
  { text: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius" },
  { text: "Don’t wish it were easier, wish you were better.", author: "Jim Rohn" },
  { text: "Leap, and the net will appear.", author: "John Burroughs" },
  { text: "Nothing can dim the light that shines from within.", author: "Maya Angelou" },
  { text: "If you want to fly, give up everything that weighs you down.", author: "Buddha" },
  { text: "You only fail when you stop trying.", author: "Unknown" },
  { text: "If people are doubting how far you can go, go so far that you can’t hear them anymore.", author: "Michele Ruiz" },
  { text: "Be so good they can’t ignore you.", author: "Steve Martin" },
  { text: "The expert in anything was once a beginner.", author: "Helen Hayes" },
  { text: "Take the risk or lose the chance.", author: "Unknown" },
  { text: "You can. End of story.", author: "Unknown" },
  { text: "If you think lifting is dangerous, try being weak. Being weak is dangerous.", author: "Bret Contreras" },
  { text: "Do what you have to do until you can do what you want to do.", author: "Oprah Winfrey" },
  { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { text: "Suffer the pain of discipline or suffer the pain of regret.", author: "Unknown" },
  { text: "If you want something you've never had, you must be willing to do something you've never done.", author: "Thomas Jefferson" },
  { text: "Your limitation—it’s only your imagination.", author: "Unknown" },
  { text: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
  { text: "Don’t stop when you’re tired. Stop when you’re done.", author: "Marilyn Monroe" },
  { text: "Be stronger than your excuses.", author: "Unknown" },
  { text: "Great things never come from comfort zones.", author: "Unknown" },
  { text: "Success doesn’t just find you. You have to go out and get it.", author: "Unknown" },
  { text: "The harder you work for something, the greater you’ll feel when you achieve it.", author: "Unknown" },
  { text: "Dream bigger. Do bigger.", author: "Unknown" },
  { text: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown" },
  { text: "Do something today that your future self will thank you for.", author: "Sean Patrick Flanery" },
  { text: "Little things make big days.", author: "Isabel Marant" },
  { text: "It’s going to be hard, but hard does not mean impossible.", author: "Unknown" },
  { text: "Don’t wait for opportunity. Create it.", author: "Unknown" },
  { text: "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.", author: "Unknown" },
  { text: "The key to success is to focus our conscious mind on things we desire not things we fear.", author: "Brian Tracy" },
  { text: "The pain you feel today will be the strength you feel tomorrow.", author: "Unknown" },
  { text: "We can’t become what we need to be by remaining what we are.", author: "Oprah Winfrey" },
  { text: "Faith moves mountains, but you have to keep pushing while you are praying.", author: "Mason Cooley" },
  { text: "Don’t complain, just work harder.", author: "Unknown" },
  { text: "It’s not about how bad you want it. It’s about how hard you’re willing to work for it.", author: "Unknown" },
  { text: "You don’t have to like it, you just have to do it.", author: "Unknown" },
  { text: "Nobody cares, work harder.", author: "Cam Hanes" },
  { text: "Let them sleep while you grind. Let them party while you work. The difference will show.", author: "Eric Thomas" },
  { text: "No one is going to push you except yourself.", author: "Unknown" },
  { text: "Excuses don’t get results.", author: "Unknown" },
  { text: "Think less. Do more.", author: "Unknown" },
  { text: "It's supposed to be hard. If it were easy, everyone would do it.", author: "Tom Hanks" },
  { text: "Winners train, losers complain.", author: "Unknown" },
  { text: "Motivation gets you going. Discipline keeps you growing.", author: "John C. Maxwell" },
  { text: "The world doesn’t owe you anything. You have to earn it.", author: "Unknown" },
  { text: "Your excuses are just the lies your fears have sold you.", author: "Robin Sharma" },
  { text: "The more you sweat in practice, the less you bleed in battle.", author: "Unknown" },
  { text: "Success is not for the chosen few, but for the few who choose it.", author: "Unknown" },

  // --- Even More (Random) Motivational Quotes ---
  { text: "Losers quit when they’re tired. Winners quit when they’ve won.", author: "Unknown" },
  { text: "If it’s important to you, you’ll find a way. If not, you’ll find an excuse.", author: "Unknown" },
  { text: "Some want it to happen, some wish it would happen, others make it happen.", author: "Michael Jordan" },
  { text: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
  { text: "Train insane or remain the same.", author: "Jillian Michaels" },
  { text: "If someone is better than you, work harder.", author: "Unknown" },
  { text: "Don’t blame others for your situation.", author: "Unknown" },
  { text: "If you aren’t willing to work for it, don’t complain about not having it.", author: "Unknown" },
  { text: "When you feel like quitting, remember why you started.", author: "Unknown" },
  { text: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson" },
  { text: "What you want won’t happen by accident.", author: "Unknown" },
  { text: "You’re only as strong as your next move.", author: "Unknown" },
  { text: "Be ruthless with your time. Be rare with your energy. Be limitless with your growth.", author: "Unknown" },
  { text: "Be obsessed or be average.", author: "Grant Cardone" },
  { text: "Suffer now and live the rest of your life as a champion.", author: "Muhammad Ali" },
  { text: "No pain, no gain. Shut up and train.", author: "Unknown" },
  { text: "If you want to be the best, you have to do things other people aren’t willing to do.", author: "Michael Phelps" },

  // --- Toxic Motivational Quotes (warning: blunt/harsh) ---
  { text: "No one cares about your problems, work harder.", author: "Toxic Motivation" },
  { text: "Stay broke, or get to work.", author: "Toxic Motivation" },
  { text: "Your comfort zone will kill you.", author: "Toxic Motivation" },
  { text: "Your feelings don’t pay the bills.", author: "Toxic Motivation" },
  { text: "If you want sympathy, look in the dictionary between sh*t and syphilis.", author: "Toxic Motivation" },
  { text: "Go cry, then get back to work.", author: "Toxic Motivation" },
  { text: "Life doesn’t care if you’re tired.", author: "Toxic Motivation" },
  { text: "Nobody is coming to save you.", author: "Toxic Motivation" },
  { text: "Get up. Nobody is going to do it for you.", author: "Toxic Motivation" },
  { text: "You’re losing because you’re not working hard enough.", author: "Toxic Motivation" },
  { text: "Don’t be upset about the results you didn’t get from the work you didn’t do.", author: "Toxic Motivation" },
  { text: "Excuses don’t burn calories.", author: "Toxic Motivation" },
  { text: "Dreams don’t work unless you do. No exceptions.", author: "Toxic Motivation" },
  { text: "Be stronger than your excuses.", author: "Toxic Motivation" },
  { text: "Work until your haters ask if you’re hiring.", author: "Toxic Motivation" },
  { text: "Your laziness is your enemy.", author: "Toxic Motivation" },
  { text: "Respect is earned, not given. Start earning.", author: "Toxic Motivation" },
  { text: "Victims make excuses. Winners find a way.", author: "Toxic Motivation" },
  { text: "Don’t expect results without pain.", author: "Toxic Motivation" },
  { text: "Discipline > motivation. Show up anyway.", author: "Toxic Motivation" },
  { text: "Nobody cares. Push through anyway.", author: "Toxic Motivation" },
  { text: "Be so good they can’t ignore you—even if they hate you.", author: "Toxic Motivation" },
  // --- Feel free to continue adding many more quotes here if you'd like even more! ---
];
